export {
    provideFirebase,
    FIREBASE_APP,
    FIREBASE_AUTH,
    FIREBASE_FUNCTIONS,
    provideFireAuth,
    provideFireFunctions,
    provideFireConfigApp,
    provideFireConfigInstance,
    provideFireConfig,
    FIRE_AUTH,
    FIRE_FUNCTIONS,
    FIRE_CONFIG_APP,
    FIRE_CONFIG_INSTANCE,
} from './lib/firebase-angular-adapter';
