import { Component, computed, effect, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { rxResource, toSignal } from '@angular/core/rxjs-interop';
import { catchError, map, of, pipe, switchMap, tap } from 'rxjs';
import { rxMethod } from '@ngrx/signals/rxjs-interop';

import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';

import { MountainSolApiService } from '@sol/angular/firebase/api';
import { MarkdownEditorComponent } from '../markdown-editor/markdown-editor.component';

type SaveState =
    | { status: 'idle' }
    | { status: 'saving' }
    | { status: 'success' }
    | { status: 'error'; message: string };

@Component({
    selector: 'sol-enrollment-email-content-editor',
    standalone: true,
    imports: [
        CommonModule,
        FormsModule,
        MatButtonModule,
        MatCardModule,
        MatIconModule,
        MatProgressSpinnerModule,
        MarkdownEditorComponent,
    ],
    template: `
        <div class="editor-container">
            <div class="editor-header">
                <button mat-icon-button (click)="navigateBack()">
                    <mat-icon>arrow_back</mat-icon>
                </button>
                <h1>Enrollment Confirmation Email Content</h1>
            </div>

            @if (loading()) {
                <div class="loading-container">
                    <mat-spinner diameter="48"></mat-spinner>
                    <p>Loading content...</p>
                </div>
            } @else {
                <mat-card class="info-card">
                    <mat-card-content>
                        <p>
                            This content is added to the class confirmation
                            email parents receive when they enroll a student in
                            a class from this semester.
                        </p>
                        <p>
                            If a parent enrolls in classes from multiple
                            semesters in a single transaction, the email shows a
                            section per semester, each with that semester's
                            content under its name.
                        </p>
                        <p>
                            Markdown is supported (lists, links, bold, etc.).
                            The rest of the email — receipt, transaction
                            details, footer — is generated by the system and
                            isn't editable here.
                        </p>
                    </mat-card-content>
                </mat-card>

                <mat-card class="form-card">
                    <mat-card-content>
                        <sol-markdown-editor
                            [(ngModel)]="content"
                            name="content"
                            placeholder="e.g., Reminders for what to bring, links to handouts, parking notes…"
                            [rows]="14"
                        ></sol-markdown-editor>
                    </mat-card-content>
                </mat-card>

                <div class="form-actions-bar">
                    <div class="form-actions-status">
                        @if (saveState().status === 'saving') {
                            <mat-spinner diameter="20"></mat-spinner>
                            <span>Saving...</span>
                        }
                        @if (saveState().status === 'success') {
                            <span class="save-success">
                                <mat-icon>check_circle</mat-icon>
                                Saved
                            </span>
                        }
                        @if (saveState().status === 'error') {
                            <span class="save-error">
                                <mat-icon>error</mat-icon>
                                {{ saveErrorMessage() }}
                            </span>
                        }
                    </div>
                    <button mat-button type="button" (click)="navigateBack()">
                        Cancel
                    </button>
                    <button
                        mat-raised-button
                        color="primary"
                        (click)="save()"
                        [disabled]="saveState().status === 'saving'"
                    >
                        Save
                    </button>
                </div>
            }
        </div>
    `,
    styles: [
        `
            .editor-container {
                max-width: 900px;
                margin: 0 auto;
                padding: 24px;
                display: flex;
                flex-direction: column;
                gap: 16px;
            }

            .editor-header {
                display: flex;
                align-items: center;
                gap: 8px;
            }

            .editor-header h1 {
                margin: 0;
                font-size: 24px;
            }

            .loading-container {
                display: flex;
                flex-direction: column;
                align-items: center;
                gap: 12px;
                padding: 48px 0;
            }

            .info-card p {
                margin: 0 0 8px 0;
            }

            .info-card p:last-child {
                margin-bottom: 0;
            }

            .form-actions-bar {
                display: flex;
                align-items: center;
                justify-content: flex-end;
                gap: 12px;
                padding: 8px 0;
            }

            .form-actions-status {
                margin-right: auto;
                display: flex;
                align-items: center;
                gap: 8px;
            }

            .save-success {
                color: var(--sol-success, #2d862d);
                display: inline-flex;
                align-items: center;
                gap: 4px;
            }

            .save-error {
                color: var(--sol-error, #c62828);
                display: inline-flex;
                align-items: center;
                gap: 4px;
            }
        `,
    ],
})
export class EnrollmentEmailContentEditorComponent {
    readonly #api = inject(MountainSolApiService);
    readonly #router = inject(Router);
    readonly #route = inject(ActivatedRoute);

    readonly #semesterIdFromRoute = toSignal(
        this.#route.paramMap.pipe(
            map((params) => params.get('semesterId') ?? '')
        )
    );

    content = signal('');
    saveState = signal<SaveState>({ status: 'idle' });

    readonly saveErrorMessage = computed(() => {
        const state = this.saveState();
        return state.status === 'error' ? state.message : '';
    });

    readonly #contentResource = rxResource({
        params: () => this.#semesterIdFromRoute() ?? '',
        stream: ({ params: semesterId }) => {
            if (!semesterId) return of({ content: null as string | null });
            return this.#api
                .getSemesterEnrollmentEmailContent({ semesterId })
                .pipe(catchError(() => of({ content: null })));
        },
    });

    readonly loading = computed(
        () => this.#contentResource.status() === 'loading'
    );

    constructor() {
        effect(() => {
            const result = this.#contentResource.value();
            if (result) {
                this.content.set(result.content ?? '');
            }
        });
    }

    readonly #performSave = rxMethod<string>(
        pipe(
            tap(() => this.saveState.set({ status: 'saving' })),
            switchMap((content) => {
                const semesterId = this.#semesterIdFromRoute() ?? '';
                return this.#api
                    .updateSemesterEnrollmentEmailContent({
                        semesterId,
                        content,
                    })
                    .pipe(
                        tap((result) => {
                            if (result.success) {
                                this.saveState.set({ status: 'success' });
                                setTimeout(
                                    () =>
                                        this.saveState.set({ status: 'idle' }),
                                    3000
                                );
                            } else {
                                this.saveState.set({
                                    status: 'error',
                                    message: 'Failed to save',
                                });
                            }
                        }),
                        catchError((err) => {
                            this.saveState.set({
                                status: 'error',
                                message:
                                    err?.message ??
                                    'An unexpected error occurred',
                            });
                            return of(null);
                        })
                    );
            })
        )
    );

    save() {
        this.#performSave(this.content());
    }

    navigateBack() {
        const semesterId = this.#semesterIdFromRoute();
        this.#router.navigate(['/admin/classes/management'], {
            queryParams: semesterId ? { semesterId } : {},
        });
    }
}
