import {
    Component,
    computed,
    effect,
    ElementRef,
    inject,
    signal,
    viewChild,
} from '@angular/core';

import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { rxResource, toSignal } from '@angular/core/rxjs-interop';
import { catchError, map, of, pipe, switchMap, tap } from 'rxjs';
import { rxMethod } from '@ngrx/signals/rxjs-interop';

import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';

import {
    MountainSolApiService,
    type SemesterEmailAttachment,
} from '@sol/angular/firebase/api';
import { previewEnrollmentEmail } from '@sol/ts/enrollment-email-template';
import { MarkdownEditorComponent } from '../markdown-editor/markdown-editor.component';

type SaveState =
    | { status: 'idle' }
    | { status: 'saving' }
    | { status: 'success' }
    | { status: 'error'; message: string };

type AttachmentState =
    | { status: 'idle' }
    | { status: 'uploading'; filename: string }
    | { status: 'deleting'; storagePath: string }
    | { status: 'error'; message: string };

type TestSendState =
    | { status: 'idle' }
    | { status: 'sending' }
    | { status: 'sent'; sentTo: string }
    | { status: 'error'; message: string };

@Component({
    selector: 'sol-enrollment-email-content-editor',
    standalone: true,
    imports: [
        FormsModule,
        MatButtonModule,
        MatCardModule,
        MatIconModule,
        MatProgressSpinnerModule,
        MarkdownEditorComponent,
    ],
    template: `
        <div class="editor-container">
            <div class="editor-header">
                <button mat-icon-button (click)="navigateBack()">
                    <mat-icon>arrow_back</mat-icon>
                </button>
                <h1>Enrollment Confirmation Email Content</h1>
            </div>

            @if (loading()) {
                <div class="loading-container">
                    <mat-spinner diameter="48"></mat-spinner>
                    <p>Loading content...</p>
                </div>
            } @else {
                <mat-card class="info-card">
                    <mat-card-content>
                        <p>
                            This content is added to the class confirmation
                            email parents receive when they enroll a student in
                            a class from
                            <strong>{{ semesterName() }}</strong
                            >.
                        </p>
                        <p>
                            If a parent enrolls in classes from multiple
                            semesters in a single transaction, the email shows a
                            section per semester, each under that semester's
                            name. Attachments from all involved semesters are
                            included on the email.
                        </p>
                        <p>
                            Markdown is supported (lists, links, bold, etc.).
                            The rest of the email — receipt, transaction
                            details, footer — is generated by the system and
                            isn't editable here.
                        </p>
                    </mat-card-content>
                </mat-card>

                <div class="editor-grid">
                    <div class="left-column">
                        <mat-card class="form-card">
                            <mat-card-header>
                                <mat-card-title>Content</mat-card-title>
                                <mat-card-subtitle
                                    >Markdown — used in the per-semester section
                                    of the email.</mat-card-subtitle
                                >
                            </mat-card-header>
                            <mat-card-content>
                                <sol-markdown-editor
                                    [(ngModel)]="content"
                                    name="content"
                                    placeholder="e.g., What to bring, links to handouts, parking notes…"
                                    [rows]="14"
                                ></sol-markdown-editor>
                            </mat-card-content>
                        </mat-card>

                        <mat-card class="form-card">
                            <mat-card-header>
                                <mat-card-title>Attachments</mat-card-title>
                                <mat-card-subtitle
                                    >PDFs attached to every confirmation email
                                    for this semester (and linked in the email
                                    body).</mat-card-subtitle
                                >
                            </mat-card-header>
                            <mat-card-content>
                                <input
                                    #fileInput
                                    type="file"
                                    accept="application/pdf"
                                    hidden
                                    (change)="onFileSelected($event)"
                                />
                                <button
                                    mat-stroked-button
                                    type="button"
                                    (click)="fileInput.click()"
                                    [disabled]="
                                        attachmentState().status ===
                                            'uploading' ||
                                        attachmentState().status === 'deleting'
                                    "
                                >
                                    <mat-icon>upload_file</mat-icon>
                                    Upload PDF
                                </button>

                                @if (attachmentState().status === 'uploading') {
                                    <div class="attachment-status">
                                        <mat-spinner
                                            diameter="20"
                                        ></mat-spinner>
                                        <span
                                            >Uploading
                                            {{ uploadingFilename() }}…</span
                                        >
                                    </div>
                                }
                                @if (attachmentState().status === 'error') {
                                    <div class="attachment-status error">
                                        <mat-icon>error</mat-icon>
                                        <span>{{
                                            attachmentErrorMessage()
                                        }}</span>
                                    </div>
                                }

                                @if (attachments().length === 0) {
                                    <p class="attachment-empty">
                                        No attachments yet.
                                    </p>
                                } @else {
                                    <ul class="attachment-list">
                                        @for (
                                            a of attachments();
                                            track a.storagePath
                                        ) {
                                            <li>
                                                <mat-icon class="pdf-icon"
                                                    >picture_as_pdf</mat-icon
                                                >
                                                <a
                                                    [href]="a.url"
                                                    target="_blank"
                                                    rel="noopener"
                                                    >{{ a.name }}</a
                                                >
                                                <button
                                                    mat-icon-button
                                                    type="button"
                                                    color="warn"
                                                    (click)="
                                                        deleteAttachment(a)
                                                    "
                                                    [disabled]="
                                                        attachmentState()
                                                            .status !== 'idle'
                                                    "
                                                    matTooltip="Remove attachment"
                                                >
                                                    <mat-icon>delete</mat-icon>
                                                </button>
                                            </li>
                                        }
                                    </ul>
                                }
                            </mat-card-content>
                        </mat-card>
                    </div>

                    <div class="right-column">
                        <mat-card class="preview-card">
                            <mat-card-header>
                                <mat-card-title>Preview</mat-card-title>
                                <mat-card-subtitle
                                    >Live render of the actual confirmation
                                    email HTML with sample enrollment
                                    data.</mat-card-subtitle
                                >
                            </mat-card-header>
                            <mat-card-content>
                                <iframe
                                    #previewFrame
                                    class="preview-frame"
                                    [srcdoc]="previewHtml()"
                                    sandbox="allow-same-origin"
                                    title="Email preview"
                                ></iframe>
                            </mat-card-content>
                        </mat-card>
                    </div>
                </div>

                <div class="form-actions-bar">
                    <div class="form-actions-status">
                        @if (saveState().status === 'saving') {
                            <mat-spinner diameter="20"></mat-spinner>
                            <span>Saving...</span>
                        }
                        @if (saveState().status === 'success') {
                            <span class="save-success">
                                <mat-icon>check_circle</mat-icon>
                                Saved
                            </span>
                        }
                        @if (saveState().status === 'error') {
                            <span class="save-error">
                                <mat-icon>error</mat-icon>
                                {{ saveErrorMessage() }}
                            </span>
                        }
                        @if (testSendState().status === 'sending') {
                            <mat-spinner diameter="20"></mat-spinner>
                            <span>Sending test…</span>
                        }
                        @if (testSendState().status === 'sent') {
                            <span class="save-success">
                                <mat-icon>mark_email_read</mat-icon>
                                Test sent to {{ testSentRecipient() }}
                            </span>
                        }
                        @if (testSendState().status === 'error') {
                            <span class="save-error">
                                <mat-icon>error</mat-icon>
                                {{ testSendErrorMessage() }}
                            </span>
                        }
                    </div>
                    <button
                        mat-stroked-button
                        type="button"
                        (click)="sendTest()"
                        [disabled]="
                            saveState().status === 'saving' ||
                            testSendState().status === 'sending'
                        "
                        matTooltip="Send the saved version of this email to your own admin address. Save first if you want to test unsaved edits."
                    >
                        <mat-icon>send</mat-icon>
                        Send test to me
                    </button>
                    <button mat-button type="button" (click)="navigateBack()">
                        Cancel
                    </button>
                    <button
                        mat-raised-button
                        color="primary"
                        (click)="save()"
                        [disabled]="saveState().status === 'saving'"
                    >
                        Save
                    </button>
                </div>
            }
        </div>
    `,
    styles: [
        `
            .editor-container {
                max-width: 1200px;
                margin: 0 auto;
                padding: 24px;
                display: flex;
                flex-direction: column;
                gap: 16px;
            }
            .editor-header {
                display: flex;
                align-items: center;
                gap: 8px;
            }
            .editor-header h1 {
                margin: 0;
                font-size: 24px;
            }
            .loading-container {
                display: flex;
                flex-direction: column;
                align-items: center;
                gap: 12px;
                padding: 48px 0;
            }
            .info-card p {
                margin: 0 0 8px 0;
            }
            .info-card p:last-child {
                margin-bottom: 0;
            }
            .editor-grid {
                display: grid;
                grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);
                gap: 16px;
            }
            @media (max-width: 1024px) {
                .editor-grid {
                    grid-template-columns: 1fr;
                }
            }
            .left-column,
            .right-column {
                display: flex;
                flex-direction: column;
                gap: 16px;
                min-width: 0;
            }
            .preview-frame {
                width: 100%;
                min-height: 600px;
                border: 1px solid var(--sol-input-border, #ccc);
                border-radius: 4px;
                background: white;
            }
            .attachment-status {
                margin-top: 12px;
                display: flex;
                align-items: center;
                gap: 8px;
            }
            .attachment-status.error {
                color: var(--sol-error, #c62828);
            }
            .attachment-empty {
                color: var(--sol-on-surface-variant, #666);
                margin-top: 12px;
            }
            .attachment-list {
                list-style: none;
                padding: 0;
                margin: 12px 0 0;
            }
            .attachment-list li {
                display: flex;
                align-items: center;
                gap: 8px;
                padding: 4px 0;
            }
            .attachment-list a {
                flex: 1;
                overflow: hidden;
                text-overflow: ellipsis;
                white-space: nowrap;
            }
            .pdf-icon {
                color: var(--sol-error, #c62828);
            }
            .form-actions-bar {
                display: flex;
                align-items: center;
                justify-content: flex-end;
                gap: 12px;
                padding: 8px 0;
                flex-wrap: wrap;
            }
            .form-actions-status {
                margin-right: auto;
                display: flex;
                align-items: center;
                gap: 8px;
            }
            .save-success {
                color: var(--sol-success, #2d862d);
                display: inline-flex;
                align-items: center;
                gap: 4px;
            }
            .save-error {
                color: var(--sol-error, #c62828);
                display: inline-flex;
                align-items: center;
                gap: 4px;
            }
        `,
    ],
})
export class EnrollmentEmailContentEditorComponent {
    readonly #api = inject(MountainSolApiService);
    readonly #router = inject(Router);
    readonly #route = inject(ActivatedRoute);

    readonly fileInput = viewChild<ElementRef<HTMLInputElement>>('fileInput');

    readonly #semesterIdFromRoute = toSignal(
        this.#route.paramMap.pipe(
            map((params) => params.get('semesterId') ?? '')
        )
    );

    content = signal('');
    semesterName = signal('This Semester');
    attachments = signal<Array<SemesterEmailAttachment>>([]);

    saveState = signal<SaveState>({ status: 'idle' });
    attachmentState = signal<AttachmentState>({ status: 'idle' });
    testSendState = signal<TestSendState>({ status: 'idle' });

    readonly saveErrorMessage = computed(() => {
        const s = this.saveState();
        return s.status === 'error' ? s.message : '';
    });
    readonly attachmentErrorMessage = computed(() => {
        const s = this.attachmentState();
        return s.status === 'error' ? s.message : '';
    });
    readonly uploadingFilename = computed(() => {
        const s = this.attachmentState();
        return s.status === 'uploading' ? s.filename : '';
    });
    readonly testSendErrorMessage = computed(() => {
        const s = this.testSendState();
        return s.status === 'error' ? s.message : '';
    });
    readonly testSentRecipient = computed(() => {
        const s = this.testSendState();
        return s.status === 'sent' ? s.sentTo : '';
    });

    readonly previewHtml = computed(() => {
        return previewEnrollmentEmail({
            semesterName: this.semesterName(),
            enrollmentEmailContent: this.content(),
            attachments: this.attachments().map((a) => ({
                name: a.name,
                url: a.url,
            })),
        }).html;
    });

    readonly #contentResource = rxResource({
        params: () => this.#semesterIdFromRoute() ?? '',
        stream: ({ params: semesterId }) => {
            if (!semesterId) {
                return of({
                    semesterName: 'This Semester',
                    content: null as string | null,
                    attachments: [] as Array<SemesterEmailAttachment>,
                });
            }
            return this.#api
                .getSemesterEnrollmentEmailContent({ semesterId })
                .pipe(
                    catchError(() =>
                        of({
                            semesterName: 'This Semester',
                            content: null as string | null,
                            attachments: [] as Array<SemesterEmailAttachment>,
                        })
                    )
                );
        },
    });

    readonly loading = computed(
        () => this.#contentResource.status() === 'loading'
    );

    constructor() {
        effect(() => {
            const result = this.#contentResource.value();
            if (result) {
                this.content.set(result.content ?? '');
                this.semesterName.set(result.semesterName ?? 'This Semester');
                this.attachments.set(result.attachments ?? []);
            }
        });
    }

    readonly #performSave = rxMethod<string>(
        pipe(
            tap(() => this.saveState.set({ status: 'saving' })),
            switchMap((content) => {
                const semesterId = this.#semesterIdFromRoute() ?? '';
                return this.#api
                    .updateSemesterEnrollmentEmailContent({
                        semesterId,
                        content,
                    })
                    .pipe(
                        tap((result) => {
                            if (result.success) {
                                this.saveState.set({ status: 'success' });
                                setTimeout(
                                    () =>
                                        this.saveState.set({
                                            status: 'idle',
                                        }),
                                    3000
                                );
                            } else {
                                this.saveState.set({
                                    status: 'error',
                                    message: 'Failed to save',
                                });
                            }
                        }),
                        catchError((err) => {
                            this.saveState.set({
                                status: 'error',
                                message:
                                    err?.message ??
                                    'An unexpected error occurred',
                            });
                            return of(null);
                        })
                    );
            })
        )
    );

    save() {
        this.#performSave(this.content());
    }

    onFileSelected(event: Event) {
        const input = event.target as HTMLInputElement;
        const file = input.files?.[0];
        if (!file) return;

        if (file.type !== 'application/pdf') {
            this.attachmentState.set({
                status: 'error',
                message: 'Only PDF files are accepted.',
            });
            input.value = '';
            return;
        }

        this.attachmentState.set({
            status: 'uploading',
            filename: file.name,
        });

        const reader = new FileReader();
        reader.onerror = () => {
            this.attachmentState.set({
                status: 'error',
                message: 'Failed to read file.',
            });
            input.value = '';
        };
        reader.onload = () => {
            const result = reader.result;
            if (typeof result !== 'string') {
                this.attachmentState.set({
                    status: 'error',
                    message: 'Unexpected file read result.',
                });
                input.value = '';
                return;
            }
            const base64 = result.split(',')[1] ?? '';
            const semesterId = this.#semesterIdFromRoute() ?? '';
            this.#api
                .uploadSemesterEmailAttachment({
                    semesterId,
                    filename: file.name,
                    fileBase64: base64,
                })
                .subscribe({
                    next: (response) => {
                        this.attachments.set(response.attachments);
                        this.attachmentState.set({ status: 'idle' });
                        input.value = '';
                    },
                    error: (err) => {
                        this.attachmentState.set({
                            status: 'error',
                            message: err?.message ?? 'Upload failed',
                        });
                        input.value = '';
                    },
                });
        };
        reader.readAsDataURL(file);
    }

    deleteAttachment(attachment: SemesterEmailAttachment) {
        const semesterId = this.#semesterIdFromRoute() ?? '';
        if (!semesterId) return;
        this.attachmentState.set({
            status: 'deleting',
            storagePath: attachment.storagePath,
        });
        this.#api
            .deleteSemesterEmailAttachment({
                semesterId,
                storagePath: attachment.storagePath,
            })
            .subscribe({
                next: (response) => {
                    this.attachments.set(response.attachments);
                    this.attachmentState.set({ status: 'idle' });
                },
                error: (err) => {
                    this.attachmentState.set({
                        status: 'error',
                        message: err?.message ?? 'Delete failed',
                    });
                },
            });
    }

    sendTest() {
        const semesterId = this.#semesterIdFromRoute() ?? '';
        if (!semesterId) return;
        this.testSendState.set({ status: 'sending' });
        this.#api.sendTestEnrollmentEmail({ semesterId }).subscribe({
            next: (response) => {
                this.testSendState.set({
                    status: 'sent',
                    sentTo: response.sentTo,
                });
                setTimeout(
                    () => this.testSendState.set({ status: 'idle' }),
                    8000
                );
            },
            error: (err) => {
                this.testSendState.set({
                    status: 'error',
                    message: err?.message ?? 'Test send failed',
                });
            },
        });
    }

    navigateBack() {
        const semesterId = this.#semesterIdFromRoute();
        this.#router.navigate(['/admin/classes/management'], {
            queryParams: semesterId ? { semesterId } : {},
        });
    }
}
