export const EnrollmentClassesMap: Record<string, Array<string>> = {
    'Full day Woodscraft AND Forts': ['Woodscraft and Wildry', 'Forts 1'],
    'Half day morning Woodscraft and Wildry': ['Woodscraft and Wildry'],
    'Half day afternoon Forts, Forts, Forts!': ['Forts 1'],
    'Navigation and Medic 1': ['Nagivation and Medic 1'],
    'Full day Fishing AND Forts': ['Fishing', 'Forts 2'],
    'Half day morning Fishing': ['Fishing'],
    'Half day afternoon Forts': ['Forts 2'],
    'Full day hamping M-Th summer camp AND F-Sat Campout': [
        'Hamping',
        'Hampout',
    ],
    'Full day hamping M-F summer camp ONLY': ['Hamping'],
    'Full day Fire AND Intro Coding': ['Fire', 'Intro Coding'],
    'Half day morning Fire': ['Fire'],
    'Half day afternoon Intro Coding': ['Intro Coding'],
    'Navigation and Medic 2': ['Navigation and Medic 2'],
    'Full day Jam Band AND Woodland Stories': ['Jam Band', 'Woodland Stories'],
    'Half day morning Jam Band': ['Jam Band'],
    'Half day afternoon Woodland Stories': ['Woodland Stories'],
    'Internal Herbalism': ['Internal Herbalism'],
    'Knife Safety 1': ['Knife Safety 1'],
    'Knife Safety 2': ['Knife Safety 2'],
    'Hamping Campout': ['Hampout'],
    'Practical Herbalism': ['Practical Herbalism'],
};
