name: Deploy Firebase Functions on merge
'on':
    push:
        branches:
            - main
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: npm ci && npm run build:functions
            - uses: w9jds/firebase-action@v2.0.0
              with:
                  args: deploy --only functions
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOUNTAIN_SOL_PLATFORM }}
