name: Deploy Firebase Functions on merge
'on':
    push:
        branches:
            - main

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm ci && npm run build:functions
            - uses: w9jds/firebase-action@master
              with:
                  args: deploy --only functions --project prod
              env:
                  GCP_SA_KEY: ${{ secrets.FIREBASE_GCP_SA_KEY }}
