name: Deploy Firebase Functions Dev on merge
'on':
    push:
        branches:
            - main

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: npm ci
            - run: npx nx run functions:build
            - uses: w9jds/firebase-action@master
              with:
                  args: deploy --only functions --project dev
              env:
                  GCP_SA_KEY: ${{ secrets.FIREBASE_GCP_SA_DEV_KEY }}
