name: Deploy Firebase Functions on merge
'on':
    push:
        branches:
            - main

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                functions-set:
                    - adminEnrollments,allStudents,availableEnrollmentClasses,calculateBasket,classGroups,classesBySemester,classes,currentSemester,deleteEnrollmentDraft
                    - emails,enroll,enrollments,fullUnitsAndPaths,getCompletedUnits,getMyStudent,historicalSemesters,loadEnrollmentDraft,myEnrolledStudents,paymentToken
                    - roles,roster,semestersAvailableToEnroll,signIn,studentHealth,tshirts,updateCompletedUnits,updateEnrollmentDraft,addEmailToSolsticeList,createEnrollmentEmail,onSuccessfulEnrollDeleteDraft
        steps:
            - uses: actions/checkout@v4
            - run: npm ci
            - run: npx nx run functions:build
            - uses: w9jds/firebase-action@v13.4.0
              with:
                  args: deploy --only functions:${{ matrix.functions-set }} --project prod
              env:
                  GCP_SA_KEY: ${{ secrets.FIREBASE_GCP_SA_KEY }}
